import Head from 'next/head'
import Header from '../components/Header'
import Feed from '../components/Feed';
import Modal from '../components/Modal';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className='bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>
      <Head>
        <title>2.0 Instabros (By Gil)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Feed />

      <Modal />

    </div>
  )
}
